# Generated by Django 5.0.14 on 2026-08-07 19:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=4)),
                ('row_count', models.IntegerField()),
                ('credits_cost', models.IntegerField()),
                ('included_unrevealed', models.BooleanField(default=True)),
                ('watermark', models.BooleanField(default=False)),
                ('rows_json', models.JSONField(default=dict)),
                ('locale', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='exports_user_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='export',
            constraint=models.CheckConstraint(check=models.Q(('format__in', ['csv', 'xlsx'])), name='exports_format_check'),
        ),
        migrations.AddConstraint(
            model_name='export',
            constraint=models.CheckConstraint(check=models.Q(('row_count__gte', 0)), name='exports_row_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='export',
            constraint=models.CheckConstraint(check=models.Q(('credits_cost__gte', 0)), name='exports_credits_cost_non_negative'),
        ),
    ]
