# Generated by Django 5.0.14 on 2026-08-09 13:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter')], default='starter', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('failed_renewal', 'Failed renewal'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('chargily_subscription_id', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chargily_event_id', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('subscription_creation', 'Subscription creation'), ('subscription_renewal', 'Subscription renewal'), ('pack_purchase', 'Pack purchase')], max_length=30)),
                ('amount_dzd', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('credits_granted', models.IntegerField(blank=True, null=True)),
                ('chargily_checkout_url', models.TextField(blank=True, null=True)),
                ('chargily_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payments_user_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['subscription_creation', 'subscription_renewal', 'pack_purchase'])), name='payment_transactions_type_check'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'succeeded', 'failed', 'refunded'])), name='payment_transactions_status_check'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'failed_renewal', 'cancelled', 'expired'])), name='subscriptions_status_check'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('tier__in', ['free', 'starter'])), name='subscriptions_tier_check'),
        ),
    ]
