# Generated by Django 5.0.14 on 2026-08-10 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_paymenttransaction_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='payments_pending_created_idx'),
        ),
    ]
