# Generated by Django 5.0.14 on 2026-08-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymenttransaction_payments_pending_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # 5.4 review RP3 (Blind Hunter B3 / Edge Hunter E5): WITHOUT this
        # backfill, the first deploy of the resend_missing_receipts sweep
        # would re-enqueue a receipt for EVERY historical succeeded payment
        # (the new column defaults to NULL) — 5.3-era subscribers who already
        # received their receipt would get a duplicate email en masse.
        # Historical succeeded rows already got their receipts; mark them as
        # receipted (reconciled_at is the grant time; created_at as fallback
        # for legacy rows written before reconciled_at existed).
        migrations.RunSQL(
            sql=(
                "UPDATE payment_transactions "
                "SET receipt_sent_at = COALESCE(reconciled_at, created_at) "
                "WHERE status = 'succeeded'"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
