# Generated by Django 5.0.14 on 2026-08-01 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('ar', 'Arabic'), ('fr', 'French'), ('en', 'English')], default='ar', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='SingleUseToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify', 'Email verification'), ('reset', 'Password reset')], default='verify', max_length=10)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_use_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'single_use_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
