# Generated by Django 5.0.14 on 2026-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_locale_alter_user_tier_singleusetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checklist_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
