# Generated by Django 5.0.14 on 2026-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_checklist_dismissed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_banner_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
