# Generated by Django 5.0.14 on 2026-08-04 10:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=64)),
                ('name_fr', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'industries',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=64)),
                ('name_fr', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('search_count', models.IntegerField(default=0)),
                ('export_rows', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_usage',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('size_band', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_normalized', models.TextField(blank=True, default='')),
                ('industry', models.ForeignKey(blank=True, db_column='industry_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='search.industry')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role', models.TextField(blank=True, null=True)),
                ('seniority', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('search_normalized', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='search.company')),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.AddConstraint(
            model_name='wilaya',
            constraint=models.CheckConstraint(check=models.Q(('code__gte', 1), ('code__lte', 58)), name='wilayas_code_range'),
        ),
        migrations.AddField(
            model_name='company',
            name='wilaya_code',
            field=models.ForeignKey(blank=True, db_column='wilaya_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='search.wilaya'),
        ),
        migrations.AddConstraint(
            model_name='dailyusage',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='daily_usage_user_date_unique'),
        ),
    ]
