# Generated by Django 5.0.14 on 2026-08-06 06:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_industry_seed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('people', 'people'), ('company', 'company')], max_length=10)),
                ('filters', models.JSONField(default=dict)),
                ('sort', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_searches',
            },
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['people', 'company'])), name='saved_searches_type_check'),
        ),
    ]
