# Generated by Django 5.0.14 on 2026-08-06 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('free_signup', 'Free signup'), ('subscription_grant', 'Subscription grant'), ('pack_grant', 'Pack grant'), ('promotional_grant', 'Promotional grant'), ('reveal_debit', 'Reveal debit'), ('export_row_debit', 'Export row debit'), ('expiry', 'Expiry')], max_length=24)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('pool', models.CharField(choices=[('subscription', 'Subscription'), ('pack', 'Pack')], default='subscription', max_length=14)),
                ('reference_id', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('people', 'People'), ('company', 'Company')], max_length=10)),
                ('record_id', models.TextField()),
                ('credit_cost', models.IntegerField(default=1)),
                ('was_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reveals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reveals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.CheckConstraint(check=models.Q(('event_type__in', ['free_signup', 'subscription_grant', 'pack_grant', 'promotional_grant', 'reveal_debit', 'export_row_debit', 'expiry'])), name='credit_ledger_event_type_check'),
        ),
        migrations.AddConstraint(
            model_name='creditledger',
            constraint=models.CheckConstraint(check=models.Q(('pool__in', ['subscription', 'pack'])), name='credit_ledger_pool_check'),
        ),
        migrations.AddConstraint(
            model_name='reveal',
            constraint=models.CheckConstraint(check=models.Q(('record_type__in', ['people', 'company'])), name='reveals_record_type_check'),
        ),
        migrations.AddConstraint(
            model_name='reveal',
            constraint=models.UniqueConstraint(condition=models.Q(('was_free', False)), fields=('user', 'record_type', 'record_id'), name='reveals_user_record_paid_unique'),
        ),
    ]
