# Generated by Django 5.0.14 on 2026-08-07 11:02

from typing import Any

from django.db import migrations
from django.db.models import Sum


def backfill(apps: Any, schema_editor: Any) -> None:
    """Restore AD-4 source-of-truth for 2.2-era signups.

    Users granted free credits before the ledger existed have a cache value
    but no ledger row. Reconcile per user: insert a free_signup row whose
    amount closes the gap `sum(ledger) == credits_balance` — the invariant
    every later read depends on. The amount is the REMAINING cache (never a
    hardcoded 15): a user who already spent credits before the ledger
    existed must not be double-granted, and a user with unrelated ledger
    rows (e.g. a promotional grant) still gets the missing free credits.
    """
    user_model = apps.get_model('accounts', 'User')
    ledger_model = apps.get_model('credits', 'CreditLedger')
    users = user_model.objects.filter(credits_balance__gt=0).exclude(
        credit_ledger__event_type='free_signup'
    )
    for user in users.iterator():
        ledger_sum = (
            ledger_model.objects.filter(user=user).aggregate(
                total=Sum('amount')
            )['total']
            or 0
        )
        gap = user.credits_balance - ledger_sum
        if gap <= 0:
            continue
        ledger_model.objects.create(
            user=user,
            event_type='free_signup',
            amount=gap,
            balance_after=user.credits_balance,
            pool='subscription',
            description='Free signup credits (backfill)',
        )


def unbackfill(apps: Any, schema_editor: Any) -> None:
    """Reverse: remove only the backfill-marked rows (no-op in practice)."""
    ledger_model = apps.get_model('credits', 'CreditLedger')
    ledger_model.objects.filter(description='Free signup credits (backfill)').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
