# Generated by Django 5.0.14 on 2026-08-07 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_backfill_free_signup_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['user', 'created_at'], name='credit_ledger_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reveal',
            index=models.Index(fields=['user', 'record_type', 'created_at'], name='reveals_user_type_created_idx'),
        ),
    ]
